trigger: none
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
  - script: dotnet pack -o $(Build.ArtifactStagingDirectory) --include-symbols --include-source --configuration $(buildConfiguration) --version-suffix "prerelease-$(Build.BuildNumber)" src/AzureTableDataStore/AzureTableDataStore.csproj

  - task: PublishPipelineArtifact@1
    displayName: 'Publish as artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)/NugetPkg'
      artifactName: NugetPackage

  - task: DotNetCoreCLI@2
    displayName: 'Push to nuget.org'
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/NugetPkg/*.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget.org'
