trigger: none
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nuGetSourceServerUrl: 'https://api.nuget.org/v3/index.json'
  nuGetSourceServerApiKey: $(NugetApiKey) # set in the pipeline variables as a secret

steps:
  - script: dotnet pack -o $(Build.ArtifactStagingDirectory) --include-symbols --include-source --configuration $(buildConfiguration) --version-suffix "prerelease-$(Build.BuildNumber)" src/AzureTableDataStore/AzureTableDataStore.csproj

  - task: PublishPipelineArtifact@1
    displayName: 'Publish as artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: NugetPackage

  - task: DotNetCoreCLI@2
    displayName: 'Push to Nuget.org'
    inputs:
      command: custom
      custom: nuget
      arguments: >
        push $(Build.ArtifactStagingDirectory)/*.nupkg
        -s $(NuGetSourceServerUrl)
        -k $(NuGetSourceServerApiKey)
