trigger: none
  
pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  nuGetSourceServerUrl: 'https://api.nuget.org/v3/index.json'
  # Set in the pipeline variables as a secret, because service connection with ApiKey just doesn't work.
  nuGetSourceServerApiKey: $(NugetApiKey) 

steps:
  # Version numbering is just so unbelievably difficult.
  - script: dotnet pack -o $(Build.ArtifactStagingDirectory) --include-symbols --include-source --configuration $(buildConfiguration) /p:Version=$(grep -oPm1 "(?<=<Version>)[^<]+" src/AzureTableDataStore/AzureTableDataStore.csproj)-prerelease-$(Build.BuildNumber)" src/AzureTableDataStore/AzureTableDataStore.csproj

  - task: PublishPipelineArtifact@1
    displayName: 'Publish as artifact'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifactName: NugetPackage

  # Because Nuget has some serious issues.
  - task: DotNetCoreCLI@2
    displayName: 'Push to Nuget.org'
    inputs:
      command: custom
      custom: nuget
      arguments: >
        push $(Build.ArtifactStagingDirectory)/*.nupkg
        -s $(NuGetSourceServerUrl)
        -k $(NuGetSourceServerApiKey)
